// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEUApVDjiFb_XD2hAG4a3wfuwkEL6epSQ',
    appId: '1:201931913533:web:a5004e6ca74344e5ceed54',
    messagingSenderId: '201931913533',
    projectId: 'newquizapp-eb48b',
    authDomain: 'newquizapp-eb48b.firebaseapp.com',
    storageBucket: 'newquizapp-eb48b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl8qHAjEiTErzirnpivjMkrLYBYzpURUg',
    appId: '1:201931913533:android:4ab77e82278b9e3dceed54',
    messagingSenderId: '201931913533',
    projectId: 'newquizapp-eb48b',
    storageBucket: 'newquizapp-eb48b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlonPyj9aLVhnS4fYsT93J6joOSA-VRts',
    appId: '1:201931913533:ios:becd9dd9d117999dceed54',
    messagingSenderId: '201931913533',
    projectId: 'newquizapp-eb48b',
    storageBucket: 'newquizapp-eb48b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlonPyj9aLVhnS4fYsT93J6joOSA-VRts',
    appId: '1:201931913533:ios:becd9dd9d117999dceed54',
    messagingSenderId: '201931913533',
    projectId: 'newquizapp-eb48b',
    storageBucket: 'newquizapp-eb48b.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEUApVDjiFb_XD2hAG4a3wfuwkEL6epSQ',
    appId: '1:201931913533:web:7e6b83d64cbe981dceed54',
    messagingSenderId: '201931913533',
    projectId: 'newquizapp-eb48b',
    authDomain: 'newquizapp-eb48b.firebaseapp.com',
    storageBucket: 'newquizapp-eb48b.firebasestorage.app',
  );
}
